version: "3.6"
services:

  vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    env_file:
      - ./config/vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    dns:
      - 172.177.0.10
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - /lib/modules:/lib/modules:ro

  odoo:
    restart: always
    container_name: odoo
    image: ghcr.io/itmo0project0management/odoo:16.0
    command: -u learning_projects -d odoo
    ports:
      - "80:8069"
    volumes:
      - ./data/odoo:/var/lib/odoo
        - ./config/odoo.prod.conf:/etc/odoo/odoo.conf
        - ./addons:/mnt/extra-addons

  postgres:
    restart: always
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "WLgxqy4gy94HrJB6LSma"
      POSTGRES_USER: "odoo"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata

  pgadmin:
    restart: always
    image: dpage/pgadmin4:6.4
    environment:
      HOSTNAMES: pgadmin.itmo-learning-projects.ru
      PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
      PGADMIN_DEFAULT_PASSWORD: 9tkgWIxz3nknyoIlBQYL

  maildev:
    restart: always
    container_name: maildev
    image: maildev/maildev:latest
    environment:
      HOSTNAMES: maildev.itmo-learning-projects.ru

  dps:
    image: defreitas/dns-proxy-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    environment:
      - MG_LOG_LEVEL=ERROR
    hostname: dns.itmo-learning-projects.ru
    networks:
      default:
        ipv4_address: 172.177.0.10

networks:
  default:
    name: lp_network
    ipam:
      config:
        - subnet: 172.177.0.0/16
